### ISSUE TITLE
patch migration failed

### ISSUE THREAD

**Issue by fatihkoca9** [NovatecConsulting/camunda-process-instance-migrator#28]
Hello, 

 I had 2 Definition Version on the same Tag version (1.0.3). Migration did not pass. So I deleted a deployment to keep only one (by checking the cascade box when deleting).

When I try again to migrate to a new Tag version (1.0.4) the process instances get stuck on 1.0.3.

Here the error code:

I don't understand because I deleted 1 deployment with cascade option.

Here the logs : 
camunda_1  | 2021-06-30 12:44:44 - Starting migration for instances with process definition key Process_05g4419
camunda_1  | 2021-06-30 12:44:44 - Process instances BEFORE migration with process definition key Process_05g4419
camunda_1  | 2021-06-30 12:44:44 - processDefinitionId: Process_05g4419:6:f0c214f8-d989-11eb-800d-0242ac1c0002, versionTag: 1.0.4, count 4, businessKeys: null,null,null,null
camunda_1  | 2021-06-30 12:44:44 - Newest version for process definition key Process_05g4419 is 1.0.5. Attempting migration.
camunda_1  | 2021-06-30 12:44:45 - Successfully migrated process instance with id 2805e848-d58e-11eb-b0b4-0242ac160002 and businessKey null from version 1.0.4 to version 1.0.5
camunda_1  | 2021-06-30 12:44:45 - Successfully migrated process instance with id 341996de-cf44-11eb-92a4-0242c0a86002 and businessKey null from version 1.0.4 to version 1.0.5
camunda_1  | 2021-06-30 12:44:46 - Successfully migrated process instance with id bc968d4b-d00c-11eb-bbf5-0242c0a8b002 and businessKey null from version 1.0.4 to version 1.0.5
camunda_1  | 2021-06-30 12:44:46 - Successfully migrated process instance with id ed3d7c25-d02c-11eb-a766-0242c0a8d002 and businessKey null from version 1.0.4 to version 1.0.5
camunda_1  | 2021-06-30 12:44:46 - Process instances AFTER migration with process definition key Process_05g4419
camunda_1  | 2021-06-30 12:44:46 - processDefinitionId: Process_05g4419:7:1a3d1225-d990-11eb-818e-0242ac1d0002, versionTag: 1.0.5, count 4, businessKeys: null,null,null,null
camunda_1  | 2021-06-30 12:44:46 - Starting migration for instances with process definition key Process_05g7318
camunda_1  | 2021-06-30 12:44:46 - Process instances BEFORE migration with process definition key Process_05g7318
camunda_1  | 2021-06-30 12:44:46 - processDefinitionId: Process_05g7318:4:c2f056d3-cf61-11eb-a092-0242c0a88002, versionTag: 1.0.3, count 8, businessKeys: null,null,null,null,null,null,null,null
camunda_1  | 2021-06-30 12:44:46 - Newest version for process definition key Process_05g7318 is 1.0.5. Attempting migration.
camunda_1  | java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
camunda_1  |    at info.novatec.camunda.migrator.ProcessVersion.fromString(ProcessVersion.java:22)
camunda_1  |    at info.novatec.camunda.migrator.ProcessInstanceMigrator.lambda$getOlderProcessInstances$4(ProcessInstanceMigrator.java:118)
camunda_1  |    at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
camunda_1  |    at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
camunda_1  |    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
camunda_1  |    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
camunda_1  |    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
camunda_1  |    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
camunda_1  |    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
camunda_1  |    at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
camunda_1  |    at info.novatec.camunda.migrator.ProcessInstanceMigrator.getOlderProcessInstances(ProcessInstanceMigrator.java:133)
camunda_1  |    at info.novatec.camunda.migrator.ProcessInstanceMigrator.migrateProcessInstances(ProcessInstanceMigrator.java:54)
camunda_1  |    at info.novatec.camunda.migrator.ProcessInstanceMigrator.lambda$migrateInstancesOfAllProcesses$0(ProcessInstanceMigrator.java:37)
camunda_1  |    at java.base/java.util.ArrayList.forEach(Unknown Source)
camunda_1  |    at info.novatec.camunda.migrator.ProcessInstanceMigrator.migrateInstancesOfAllProcesses(ProcessInstanceMigrator.java:37)
camunda_1  |    at fr.utbm.accueilindividu.controller.MigrateProcessController.start(MigrateProcessController.java:15)
camunda_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
camunda_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
camunda_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
camunda_1  |    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
camunda_1  |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
camunda_1  |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
camunda_1  |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
camunda_1  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
camunda_1  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
camunda_1  |    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
camunda_1  |    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
camunda_1  |    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
camunda_1  |    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
camunda_1  |    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
camunda_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
camunda_1  |    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
camunda_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
camunda_1  |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
camunda_1  |    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
camunda_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
camunda_1  |    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
camunda_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
camunda_1  |    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
camunda_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
camunda_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
camunda_1  |    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
camunda_1  |    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
camunda_1  |    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
camunda_1  |    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
camunda_1  |    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
camunda_1  |    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
camunda_1  |    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
camunda_1  |    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
camunda_1  |    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
camunda_1  |    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
camunda_1  |    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
camunda_1  |    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
camunda_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
camunda_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
camunda_1  |    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
camunda_1  |    at java.base/java.lang.Thread.run(Unknown Source)
camunda_1  | java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
camunda_1  |    at info.novatec.camunda.migrator.ProcessVersion.fromString(ProcessVersion.java:22)
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
camunda_1  |    at info.novatec.camunda.migrator.ProcessVersion.fromString(ProcessVersion.java:22)at info.novatec.camunda.migrator.ProcessInstanceMigrator.lambda$getOlderProcessInstances$4(ProcessInstanceMigrator.java:118)

**Comment by fatihkoca9** [comment]
Can you help me to understand or to find a manual solution please?

**Comment by fatihkoca9** [comment]
![image](https://user-images.githubusercontent.com/72793538/123952321-27c5b900-d9a6-11eb-8780-a1789d19062e.png)
![image](https://user-images.githubusercontent.com/72793538/123952383-3c09b600-d9a6-11eb-9464-325fce35e45b.png)

**Comment by BenFuernrohr** [comment]
Hi @fatihkoca9,
thanks for opening the issue. 

I hope I was able to interpret the stacktrace correctly. Apparently the migration seems to be working fine for the process with the key 'Process_05g4419', and the error happens  when attempting to migrate process instances with the key 'Process_05g7318'.
For that key, apparently the migrator attempts to parse a vversion tag that has a faulty format, but is not null (because our code filters out null tags).  This causes the ArrayIndexOutOfBoundsException to occur.
What's weird is that the error occurs in line 22 of ProcessVersion, which indicates that the tag still contains exactly one '.'. Otherwise the error would occur in line 21. That would make more sense, because it could be explained with the tag being an empty string.

This suggests that SOME deployed version of Process_05g4419 has a faulty version tag. It does not have to be the one with the active process instances. In fact, your screenshot shows, that the active process instances are from Definition Version 4, which has the tag 1.0.3, which is fine.
Could you check if maybe the tags for Definition Version 5 or 6 are faulty? If one of those refer to the deleted deployment, then that might also explain things.

In any way we should aim to make this aspect of the migrator more robust. So thank you for pointing that out so we can improve the tool :+1:

**Comment by BenFuernrohr** [comment]
Hi @fatihkoca9,

I´ve created a new release that should resolve your issue. Please try using version 1.0.2 and kindly tell me whether that fixed your problem.

**Comment by fatihkoca9** [comment]
Hi @BenFuernrohr. Its perfect thank you !!!!
Have a nice day

**Comment by BenFuernrohr** [comment]
You´re welcome and thanks for helping us improve the tool! :+1:
